import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { AppShell, PageHeader } from "@/components/app-shell";
import { Badge, Button, Card } from "@/components/ui-bits";
import { reportsService, type ReportRecord, type ReportType } from "@/lib/reports-service";
import { teamAnalyticsService } from "@/lib/team-analytics-service";
import { Calendar, Download, FileText, Loader2, Plus, RefreshCw, Share2 } from "lucide-react";

export const Route = createFileRoute("/reports")({ head: () => ({ meta: [{ title: "Reports · GitInsight AI" }] }), component: Reports });
const control = "h-10 rounded-xl border border-border bg-card px-3 text-sm";
const types: ReportType[] = ["Team Performance", "Repository Health", "AI Insights", "Project Summary", "Developer Performance"];

function Reports() {
  const [reports, setReports] = useState<ReportRecord[]>([]); const [repositories, setRepositories] = useState<Awaited<ReturnType<typeof teamAnalyticsService.getRepositories>>>([]); const [open, setOpen] = useState(false); const [generating, setGenerating] = useState(false); const [selected, setSelected] = useState<ReportRecord | null>(null); const [type, setType] = useState<ReportType>(types[0]); const [period, setPeriod] = useState("Last 30 days"); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); setError(""); try { const [saved, repos] = await Promise.all([reportsService.list(), teamAnalyticsService.getRepositories()]); setReports(saved); setRepositories(repos); if (!saved.length && repos[0]) { const analytics = await teamAnalyticsService.getAnalytics({ repository: repos[0].fullName }); const live = await reportsService.generate({ reportType: "Team Performance", repositoryId: repos[0].fullName, period: "Last 30 days", include: { contribution: true, issues: true, pullRequests: true, reviews: true, aiInsights: true, charts: true } }, analytics); setReports([live]); } } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load GitHub reports."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  useEffect(() => { const refresh = () => void load(); window.addEventListener("gitinsight-auto-refresh", refresh); return () => window.removeEventListener("gitinsight-auto-refresh", refresh); }, []);
  const generate = async () => { setGenerating(true); setError(""); try { const repository = repositories[0]; if (!repository) throw new Error("Connect a GitHub repository before generating a report."); const analytics = await teamAnalyticsService.getAnalytics({ repository: repository.fullName, dateRange: period === "Last 7 days" ? "7d" : period === "Last 90 days" ? "90d" : period === "This year" ? "year" : "30d" }); const created = await reportsService.generate({ reportType: type, repositoryId: repository.fullName, period, include: { contribution: true, issues: true, pullRequests: true, reviews: true, aiInsights: true, charts: true } }, analytics); setReports((items) => [created, ...items.filter((item) => item.id !== created.id)]); setSelected(created); setOpen(false); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to generate the report."); } finally { setGenerating(false); } };
  return <AppShell><PageHeader title="Reports" subtitle="Generate, view, and export project intelligence reports." actions={<Button onClick={() => setOpen(true)}><Plus className="h-4 w-4" /> Generate Report</Button>} />{error && <Card className="mb-5 p-4 flex items-center justify-between gap-4"><span className="text-sm text-danger">{error}</span><Button variant="secondary" className="h-9" onClick={() => void load()}><RefreshCw className="h-4 w-4" /> Retry</Button></Card>}{loading ? <div className="grid place-items-center py-24"><Loader2 className="h-7 w-7 animate-spin text-brand" /></div> : <><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{reports.map((report) => <ReportCard key={report.id} report={report} onView={() => setSelected(report)} />)}</div>{!reports.length && <Card className="p-10 text-center mt-5"><p className="font-medium">No reports available</p><p className="text-sm text-muted-foreground mt-1">Connect GitHub repositories to generate a report from real activity.</p></Card>}</>}{open && <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><Card className="w-full max-w-lg p-6"><div className="flex items-center justify-between"><div className="text-lg font-semibold">Generate report</div><button className="text-muted-foreground" onClick={() => setOpen(false)}>Close</button></div><div className="mt-5 space-y-4"><label className="block text-sm">Report type<select className={`${control} mt-1 w-full`} value={type} onChange={(event) => setType(event.target.value as ReportType)}>{types.map((item) => <option key={item}>{item}</option>)}</select></label><label className="block text-sm">Repository<select className={`${control} mt-1 w-full`} disabled><option>{repositories[0]?.fullName ?? "No connected repositories"}</option></select></label><label className="block text-sm">Period<select className={`${control} mt-1 w-full`} value={period} onChange={(event) => setPeriod(event.target.value)}><option>Last 7 days</option><option>Last 30 days</option><option>Last 90 days</option><option>This year</option></select></label></div><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => void generate()} disabled={generating || !repositories.length}>{generating ? <><Loader2 className="h-4 w-4 animate-spin" /> Generating...</> : "Generate Report"}</Button></div></Card></div>}{selected && <ReportViewer report={selected} onClose={() => setSelected(null)} />}</AppShell>;
}

function ReportCard({ report, onView }: { report: ReportRecord; onView: () => void }) { return <Card className="p-5"><div className="flex items-center justify-between"><div className="h-10 w-10 rounded-xl bg-brand/10 text-brand grid place-items-center"><FileText className="h-5 w-5" /></div><Badge tone="success">{report.status}</Badge></div><div className="mt-4 font-semibold">{report.name}</div><div className="text-sm text-muted-foreground mt-1">{report.reportType} · {report.developers} contributors · {report.repositoryName ?? "GitHub repository"}</div><div className="mt-3 flex items-center gap-1.5 text-xs text-muted-foreground"><Calendar className="h-3.5 w-3.5" /> {report.periodStart} - {report.periodEnd}</div><div className="mt-4 flex flex-wrap gap-2"><Button variant="secondary" className="h-9 px-3" onClick={onView}>View</Button><Button variant="secondary" className="h-9 px-3" onClick={() => downloadReport(report, "pdf")}><Download className="h-4 w-4" /> PDF</Button><Button variant="ghost" className="h-9 px-3" onClick={() => downloadReport(report, "csv")}><Download className="h-4 w-4" /> CSV</Button></div></Card>; }
function ReportViewer({ report, onClose }: { report: ReportRecord; onClose: () => void }) { const metrics = report.metrics ?? { commits: 0, pullRequests: 0, issues: 0, reviews: 0 }; return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/40 p-4"><Card className="mx-auto max-w-3xl p-6 my-8"><div className="flex justify-between"><div><div className="text-2xl font-semibold">{report.name}</div><div className="text-sm text-muted-foreground">{report.periodStart} - {report.periodEnd} · {report.repositoryName}</div></div><Button variant="ghost" onClick={onClose}>Close</Button></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-6">{Object.entries(metrics).map(([label, value]) => <div key={label} className="rounded-xl bg-muted/60 p-4"><div className="text-xs text-muted-foreground capitalize">{label}</div><div className="text-xl font-semibold mt-1">{value}</div></div>)}</div><div className="mt-6 rounded-xl border border-border p-5"><div className="font-semibold">Executive summary</div><p className="text-sm text-muted-foreground mt-2">This report was generated from GitHub activity for {report.repositoryName}. The metrics above reflect the selected reporting period.</p></div><div className="mt-5 flex gap-2"><Button onClick={() => downloadReport(report, "pdf")}><Download className="h-4 w-4" /> Export PDF</Button><Button variant="secondary" onClick={() => downloadReport(report, "csv")}><Download className="h-4 w-4" /> Export CSV</Button><Button variant="ghost"><Share2 className="h-4 w-4" /> Share</Button></div></Card></div>; }
function downloadReport(report: ReportRecord, format: "pdf" | "csv") { const metrics = report.metrics ?? { commits: 0, pullRequests: 0, issues: 0, reviews: 0 }; const content = format === "csv" ? [`report,repository,period,commits,pull_requests,issues,reviews`, `${report.name},${report.repositoryName ?? ""},${report.periodStart} - ${report.periodEnd},${metrics.commits},${metrics.pullRequests},${metrics.issues},${metrics.reviews}`].join("\n") : `${report.name}\nRepository: ${report.repositoryName ?? ""}\nPeriod: ${report.periodStart} - ${report.periodEnd}\nCommits: ${metrics.commits}\nPull requests: ${metrics.pullRequests}\nIssues: ${metrics.issues}\nReviews: ${metrics.reviews}`; const blob = new Blob([content], { type: format === "csv" ? "text/csv;charset=utf-8" : "application/pdf" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${report.name.replaceAll(" ", "-")}.${format}`; anchor.click(); URL.revokeObjectURL(url); }
